---
- name: Register RHEL VMs and install Insights/related
  gather_facts: no
  become: yes

  hosts: azure

  vars:
  # Explicitly telling Ansible to use Python3, because of the bug below:
  #     # https://github.com/ansible/ansible/issues/54855
  #- ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Configure auto-registration of hosts
    lineinfile:
      path: /etc/rhsm/rhsm.conf
      regexp: '^auto_registration '
      line: 'auto_registration = 1'

  - name: Speed up auto-registration of hosts
    lineinfile:
      path: /etc/rhsm/rhsm.conf
      regexp: '^auto_registration_interval '
      line: 'auto_registration_interval = 5'

  - name: Restart rhsmcertd to force auto_registration to kick off sooner
    ansible.builtin.systemd_service:
      name: rhsmcertd
      state: restarted

  - name: Grab some subscription-manager facts for debugging
    ansible.builtin.shell:
      cmd: 'subscription-manager facts | grep -i azure'
    register: subman_facts

  - name: Print the subscription-manager facts for debugging
    ansible.builtin.debug:
      var: subman_facts
